### ISSUE TITLE
Feature Request: Generic Simple API Integration

### ISSUE THREAD

**Issue by patrickheney** [MeridiusIX/RivalAI#184]
A request for the ability use any API provided it matches a specified interface pattern.
For example, a behavior could would call a specific API that accepted exactly 1 parameter as a string, and returned a single string as a response. I have a site that provides role-playing text using this simple pattern, and I'd like to use it. This might allow other people to do the same, or allow people to access other similarly "simple" API-sourced information.

**Comment by MeridiusIX** [comment]
The mod can already get/set "sandbox variables" which get saved to the worlds Sandbox.sbc file. With some clever work, you could probably parse values from that somehow.
