### ISSUE TITLE
Feature Request: Ability to save global data between NPCs

### ISSUE THREAD

**Issue by patrickheney** [MeridiusIX/RivalAI#185]
For example,
- Store the number of times a particular player has been encountered so that different behaviors can be activated. This would enable things like "so we meet again" chat messages and related behaviors.
- Store player responses to chat messages so that different behaviors can be activated. This would enable things like NPCs that send a chat message requesting an access code (which could be found on datapads on other NPCs) and then recording whether the player has successfully provided the access code or not. Behaviors could then be selected based on whether the player has ever provided the correct code, or perhaps if the player has provided the wrong code too many times in a given timeframe.
- Store the engagement duration with a particular player so that future engagements might be scaled appropriately. 
- Store engagement results, e.g., escape / win / lose, with a particular player, so that behaviors might be selected accordingly. So if a particular NPC always loses to a player, then perhaps when the player approaches it always attempts to flee. If a particular NPC is always attacked by a player, or always defeats a player, perhaps it is more likely to pre-emptively engage the player, rather than just waiting for the player to make the first move.

**Comment by MeridiusIX** [comment]
I don't think I would do anything at a 'per player' level, at least not unless I find a strong need for it in some of my future projects. 

There will be some loose elements of these idea in an upcoming feature called Zones (will replace territories and KPLs) that will be able to store data in them, so interactions in said zones can set certain values that the spawner and rivalai behaviors can see and act on.
