### ISSUE TITLE
Feature Request: tags to read and save a line of chat

### ISSUE THREAD

**Issue by patrickheney** [MeridiusIX/RivalAI#187]
I would like to be able to read chat in a behavior. It would be defined in a Chat Profile something like the following (multiple tags should be permitted)

[ChatMessages:What is your favorite color?]
[ReadChatResponse:FavoriteColor]

[ChatMessages:What is the airspeed velocity of an unladen swallow?]
[ReadChatResponse:Airspeed]

This would read the first line in chat that appear after the bot sends it's message (or, ideally, the first line the player types in chat after the message is delivered) and store the line in a variable with name provided by the value. In the example above, the answers are stored in "FavoriteColor" and "Airspeed".

The contents of the variable can then be used in a condition profile with these tags 
[CustomText:value] -- This names the variable we want to check
[CheckCustomText:value]  -- This compares the above named value to the provided value

For example (in a Condition Profile)
[CustomText:FavoriteColor]
[CheckCustomText:Yellow]

[CustomText:Airspeed]
[CheckCustomText:What do you mean? African or European?]

In a more practical application, this could be used to allow a player to provide an "access code" to gain safe passage past a sentry gun or fly past a drone without it engaging them. (The access codes might be found on datapads provided in other encounters.)

It could also be used to provide deeper story elements to encounters through the clever use of chat profiles and condition profiles, which could be used to create a dialog tree.

**Comment by MeridiusIX** [comment]
I've already got something like that planned, though maybe not as complex. It will use the RivalAI Command System Triggers to capture text from players so the Action system can act on it.
